import type { Metadata } from "next";
import localFont from "next/font/local";
import { Racing_Sans_One ,Bayon,Bebas_Neue} from "next/font/google";
import "./globals.css";

const racing = Racing_Sans_One({
  subsets: ["latin"],
  variable: "--font-racing",
  weight: "400",
});

const bayon = Bayon({
  subsets: ["latin"],
  variable: "--font-bayon",
  weight: "400",
});

const bebas = Bebas_Neue({
  subsets: ["latin"],
  variable: "--font-bebas",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${racing.variable} ${bayon.variable} ${bebas.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
